# Generated by Django 6.0.3 on 2026-03-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video_file', models.FileField(upload_to='tutorials/', verbose_name='Файл видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обучающее видео',
                'verbose_name_plural': 'Обучающие видео',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('face_not_in_frame', 'Лицо не в рамке'), ('face_not_detected', 'Лицо не обнаружено'), ('multiple_faces', 'Несколько лиц'), ('noise_detected', 'Обнаружен шум'), ('tab_switch', 'Переключение вкладки/экрана'), ('suspicious_eye_movement', 'Подозрительное движение глаз'), ('phone_detected', 'Использование телефона/устройств')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
            },
        ),
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('score_earned', models.PositiveIntegerField(default=0)),
                ('is_manually_graded', models.BooleanField(default=False, verbose_name='Проверено вручную')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.option')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершён'), ('TERMINATED', 'Принудительно завершён')], db_index=True, default='IN_PROGRESS', max_length=15, verbose_name='Статус')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('screen_recording', models.FileField(blank=True, null=True, upload_to='recordings/screen/')),
                ('face_recording', models.FileField(blank=True, null=True, upload_to='recordings/face/')),
                ('rules_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Правила приняты в')),
                ('workplace_ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Место подготовлено в')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.stream')),
            ],
            options={
                'verbose_name': 'Попытка сдачи',
                'verbose_name_plural': 'Попытки сдачи',
            },
        ),
    ]
