# Generated by Django 6.0.3 on 2026-03-18 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proctoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='proctoring.examattempt'),
        ),
        migrations.AddField(
            model_name='violation',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='proctoring.examattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('stream', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='answerattempt',
            unique_together={('attempt', 'question')},
        ),
        # --- production indexes (manually added) ---
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(
                fields=['stream', 'status'],
                name='attempt_stream_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(
                fields=['student', '-end_time'],
                name='attempt_student_endtime_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(
                fields=['student', '-score'],
                name='attempt_student_score_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='answerattempt',
            index=models.Index(
                fields=['attempt'],
                name='answer_attempt_idx',
            ),
        ),
    ]
