# Generated by Django 6.0.3 on 2026-03-25 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_exam_teacher_created_idx_and_more'),
        ('proctoring', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answerattempt',
            index=models.Index(fields=['attempt'], name='answer_attempt_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['stream', 'status'], name='attempt_stream_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', '-end_time'], name='attempt_student_endtime_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', '-score'], name='attempt_student_score_idx'),
        ),
    ]
