# Generated by Django 6.0.3 on 2026-03-18 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Лёгкий'), ('MEDIUM', 'Средний'), ('HARD', 'Сложный')], max_length=10, null=True, verbose_name='Сложность')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Макс. балл')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('microphone_status', models.CharField(choices=[('ON', 'Включен'), ('OFF', 'Выключен'), ('HYBRID', 'Гибридное')], default='OFF', max_length=10, verbose_name='Состояние микрофона')),
                ('require_screen_record', models.BooleanField(default=False, verbose_name='Запись экрана')),
                ('require_face_record', models.BooleanField(default=False, verbose_name='Запись лица')),
                ('max_violations', models.PositiveIntegerField(default=4, verbose_name='Макс. нарушений до аннуляции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='Изображение')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
                ('type', models.CharField(choices=[('CHOICE', 'Текстовое поле (4 варианта)'), ('PHOTO_CHOICE', 'Фото ответ (4 варианта-фото)'), ('INTERACTIVE', 'Интерактивный ответ (свободный текст)')], default='CHOICE', max_length=20, verbose_name='Тип')),
                ('score', models.PositiveIntegerField(default=1, verbose_name='Балл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('expected_answer', models.TextField(blank=True, null=True, verbose_name='Ожидаемый ответ')),
                ('min_answer_length', models.PositiveIntegerField(default=0, help_text='Для INTERACTIVE. 0 = нет ограничения.', verbose_name='Мин. длина ответа (символов)')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название потока')),
                ('access_link_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mic_enabled', models.BooleanField(default=False, verbose_name='Микрофон включён (поток)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
    ]
