# Generated by Django 6.0.3 on 2026-03-18 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question'),
        ),
        migrations.AddField(
            model_name='stream',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='exams.exam'),
        ),
        # --- production indexes (manually added) ---
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(
                fields=['teacher', '-created_at'],
                name='exam_teacher_created_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(
                fields=['exam', 'order'],
                name='question_exam_order_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(
                fields=['exam'],
                name='stream_exam_idx',
            ),
        ),
    ]
