# Generated by Django 6.0.3 on 2026-03-25 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['teacher', '-created_at'], name='exam_teacher_created_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='question_exam_order_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['exam'], name='stream_exam_idx'),
        ),
    ]
